<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #1f2937; }
        h1 { font-size: 16px; margin-bottom: 0; }
        .muted { color: #6b7280; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        td, th { padding: 4px 0; text-align: left; vertical-align: top; }
        .label { width: 180px; color: #6b7280; }
        .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; }
    </style>
</head>
<body>
    <h1>{{ $business->name ?? 'KashTre Health Facility' }}</h1>
    <p class="muted">External Fulfillment / Referral — Outpatient Prescription Voucher</p>

    <table>
        <tr><td class="label">Patient ID</td><td>{{ $data['client_id'] }}</td></tr>
        <tr><td class="label">Prescribed Item</td><td>{{ $data['drug_search'] }} @if(!empty($data['strength'])) ({{ $data['strength'] }}) @endif</td></tr>
        <tr><td class="label">Dose</td><td>{{ $data['dose_amount'] }}</td></tr>
        <tr><td class="label">Route</td><td>{{ $data['route_code'] }}</td></tr>
        <tr><td class="label">Frequency</td><td>{{ $data['frequency_code'] }}</td></tr>
        <tr><td class="label">Clinical Indication</td><td>{{ $data['clinical_indication'] ?? '—' }}</td></tr>
        <tr><td class="label">Ordering Clinician</td><td>{{ $data['ordering_clinician_name'] }}</td></tr>
        <tr><td class="label">Date Issued</td><td>{{ $generatedAt->format('Y-m-d H:i') }}</td></tr>
    </table>

    <p class="footer">
        This item is not held in the facility's internal offering catalog. This voucher authorizes external
        pharmacy fulfillment. Generated by KashTre Clinical Module — Clinical Translator Engine.
    </p>
</body>
</html>
