<?php

namespace App\Domain\Units\Enums;

enum UnitClass: string
{
    case ATOMIC_BASE = 'ATOMIC_BASE';
    case PREFIXED = 'PREFIXED';
    case DERIVED_NAMED = 'DERIVED_NAMED';
    case COMPOSITE_RATIO = 'COMPOSITE_RATIO';
    case COMPOSITE_PRODUCT = 'COMPOSITE_PRODUCT';
    case COMPOSITE_POWER = 'COMPOSITE_POWER';
    case OFFSET_SCALE = 'OFFSET_SCALE';
    case LOGARITHMIC_OR_SPECIAL = 'LOGARITHMIC_OR_SPECIAL';
    case DIMENSIONLESS = 'DIMENSIONLESS';
    case COUNT_CONTEXTUAL = 'COUNT_CONTEXTUAL';
    case ARBITRARY_OR_PROCEDURE_DEFINED = 'ARBITRARY_OR_PROCEDURE_DEFINED';
    case PACKAGING_CONTEXTUAL = 'PACKAGING_CONTEXTUAL';
}
